### PR TITLE
[BUGFIX] git may return MMM instead of MM

### PR DESCRIPTION
**Pull request by williamsbdev**

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
Thanks for the PR @williamsbdev -- I'm just trying to understand this better. The server where you found this format change, can you please check and let me know if it's using a custom `.gitconfig` for the `go` user?

**Comment by williamsbdev** [comment]
@ashwanthkumar - I was not sure how to add tests for the scenario that I need, would you be able to pair with me to work on that?

**Comment by williamsbdev** [comment]
@ashwanthkumar - Just wondering if you had some time to help me with the tests or what else is needed for this PR to get merged?

**Comment by ashwanthkumar** [comment]
@williamsbdev Sorry for the late response, I'm merging this.

**Comment by ashwanthkumar** [comment]
Thanks @williamsbdev

**Pull request merged**
